### ISSUE TITLE
Cannot use plugins in passive checks

### ISSUE THREAD

**Issue by jomann09** [rechecked/rcagent#15]
Currently there is no way to run a plugin as a passive check. Will need to add a new option, rather than endpoint, you can specify plugin, with the plugin name and arguments in the options.

Something similar to this:

```
- hostname: $HOST
  servicename: Disk File Count Check
  interval: 5m
  plugin: check_disk_files.sh
  options:
    args: -d /path/to/folder -w 1000 -c 2000
```
